USE corbli;

CREATE TABLE USERINFO (
    ID INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(64) NOT NULL,
    Password VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ROLES (
    ID INT NOT NULL AUTO_INCREMENT,
    RoleDescription VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USERROLES (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    PRIMARY KEY (ID, UserID, RoleID),
    FOREIGN KEY (UserID) REFERENCES USERINFO (ID) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES ROLES (ID) 
        ON UPDATE CASCADE ON DELETE CASCADE
);
